[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.bcmath", "php82Packages.composer", "nodejs_20"]
aptPkgs = ["libgd-dev", "libpng-dev", "libzip-dev", "libjpeg-dev", "zlib1g-dev"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd", "npm install"]

[phases.build]
cmds = ["npm run build", "php artisan storage:link"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
